services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: N8N_BASIC_AUTH_USER
        value: melbayer
      - key: N8N_BASIC_AUTH_PASSWORD
        value: rock44
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_PORT
        value: 5678
